### ISSUE TITLE
Consider adding SplitResult.getauthority()

### ISSUE THREAD

**Issue by tkem** [tkem/uritools#51]
Might be more efficient than seperately calling `getuserinfo()`, `gethost()`, `getport()`.

Would return a three-item tuple consisting of `(userinfo, host, port)`.
`userinfo` might be `None` or a decoded Unicode string.
`host` might be a Unicode string or IP address (or `None`?).
`port` might be `None` or an integer (TBD: how to handle empty-but-present port?).

Parameters:
- `encoding`: Only used for `userinfo`, since hosts must be UTF-8 encoded according to RFC 3986.
- `errors`: Encoding error handling, as usual.
- `default`: three-item tuple to take defaults from (TBD: separate `userinfo`, `host`, `port` kwargs may be preferable, as in `uricompose`).

**Comment by mackness** [comment]
Hi tkem! I added submitted a PR for this. Let me know if there's anything related to my PR that I should fix. Thanks!

**Comment by tkem** [comment]
@mackness: First of all, sorry it took me that long and thanks for your interest in `uritools`! I also wanted to do an update first, so current `flake8` versions don't choke on my slouchiness...

However, there are some issue with your PR (I'm commenting here for future reference):

- Motivation for thinking about some `getauthority()` methods was that it might be more *efficient* than calling the three methods/properties individually, e.g. by splitting `authority` in one go using a regexp. However, that's just what your implementation does (invoke all three properties individually). If you try to improve this, I'd also suggest you time your code first - unless `getauthority()` isn't faster than calling all three methods separately by, say, a factor of two, adding it is probably not worth it... Sorry if this wasn't clear from the initial description (which was mostly a note to myself).
- the `host` component could also be an `ipaddress` object; unit tests should also cover this.
- the `encoding` parameter should only be used for `userinfo`; it's fixed for the other components
- the `default` parameter should either be a three-item tuple, or there should be separate `userinfo`, `host` and `port` default parameters; using the same default for all returned items makes no sense.

**Comment by mackness** [comment]
I completely understand. What do you think is the best way to test speed of calling the individual properties v.s. `getauthority()`?

I will definitely take another pass at my PR based on your feedback, thanks!

**Comment by mackness** [comment]
Thanks for uritools, I used it to teach myself Python and it taught me a lot. 👍

**Comment by tkem** [comment]
Well, thanks ;-) I hope you don't pick up too many bad habits from it...
The "standard" way to measure execution time in Python is by using the `timeit` module, for example:
```
$ python -m timeit -s 'from uritools import urisplit; p = urisplit("foo://user@example.com:8042/")' '(p.userinfo, p.host, p.port)'
100000 loops, best of 3: 2.38 usec per loop
$ python -m timeit -s 'from uritools import urisplit; p = urisplit("foo://user@example.com:8042/")' '(p.getuserinfo(), p.gethost(), p.getport())'
100000 loops, best of 3: 18.3 usec per loop
$ python -m timeit -s 'from uritools import urisplit; p = urisplit("foo://user@example.com:8042/")' 'p.getauthority()'
100000 loops, best of 3: 12.2 usec per loop
```

**Comment by tkem** [comment]
@mackness: After some pondering, I decided to add an entirely unoptimized version myself for interface symmetry. If you're still interested, feel free to try to squeeze some usecs out of it - at least you've now got some unit tests to rely on ;-)
