### ISSUE TITLE
Relax uriencode's "safe" parameter

### ISSUE THREAD

**Issue by tkem** [tkem/uritools#54]
Requiring safe to be a `bytes` object becomes unwieldy with Python 3, especially when trying to use any of the string constants. So either relax this to accept both bytes and Unicode strings, or require the platform's native `str` type.

**Comment by ilatypov** [comment]
From: Thomas KemmerSent: Sunday, February 21, 2016 3:44 PMTo: tkem/uritoolsReply To: tkem/uritoolsSubject: [uritools] Relax uriencode's "safe" parameter (#54)Requiring safe to be a bytes object becomes unwieldy with Python 3, especially when trying to use any of the string constants. So either relax this to accept both bytes and Unicode strings, or require the platform's native str type.

**Comment by tkem** [comment]
Apparently this is already implemented and just needs some unit tests...
