### ISSUE TITLE
'1abc:def' is being considered a valid relative URI

### ISSUE THREAD

**Issue by Silvanoc** [tkem/uritools#75]
**Describe the bug**
The string `"1abc:def"` is being considered a valid relative URI.
But, if I'm reading the specification right, it isn't a valid relative URI.

**Expected result**
`uritools.isrelpath("1abc:def")` returns `False`

**Actual result**
`uritools.isrelpath("1abc:def")` returns `True`

**Reproduction steps**

```python
import uritools
print(uritools.isrelpath("1abc:def"))
```

**Comment by tkem** [comment]
Please see #74.
